# Generated by Django 5.0.6 on 2024-05-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodel',
            options={'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='country',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='date',
            field=models.DateField(auto_created=True, default='2024-05-10'),
        ),
    ]
