# Generated by Django 5.0.6 on 2024-05-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('info', models.TextField()),
                ('pages', models.IntegerField()),
                ('ebook', models.FileField(upload_to='media/ebooks')),
                ('cover_photo', models.ImageField(upload_to='media/cover_photos')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
