# Generated by Django 5.0.6 on 2024-05-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='cover_photo',
            field=models.ImageField(upload_to='cover_photos'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='ebook',
            field=models.FileField(upload_to='ebooks'),
        ),
    ]
