# Generated by Django 5.0.6 on 2024-05-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_bookmodel_cover_photo_alter_bookmodel_ebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='cover_photo',
            field=models.ImageField(blank=True, default='media/cover_photos/default_photo_project_book.png', null=True, upload_to='cover_photos'),
        ),
    ]
