# Generated by Django 5.0.6 on 2024-05-10 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_bookmodel_cover_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='cover_photo',
            field=models.ImageField(blank=True, default='cover_photos/default_photo_project_book.png', null=True, upload_to='cover_photos'),
        ),
    ]
